version: '2.0'

services:
  easydeploy_local:
    build: .
    container_name: deployer
    volumes:
      - esdata1:/usr/share/easydeploy/data
    networks:
      deploynet:
        ipv4_address: 172.18.1.5

  easydeploy_remote:
    build: .
    container_name: easydeploy_server
    volumes:
      - esdata1:/usr/share/easydeploy/data
    networks:
      deploynet:
        ipv4_address: 172.18.1.4


volumes:
  esdata1:
    driver: local

networks:
  deploynet:
    driver: bridge
    ipam:
     config:
       - subnet: 172.18.1.0/16
         gateway: 172.18.1.1
